algoritmo "semnome"
var
A1, A2, media: real
inicio
Escreval ("----------------------")
Escreval ("  COLÉGIO ADVENTISTA  ")
Escreval ("----------------------")
Escreva ("Nota A1:")
Leia (A1)
Escreva ("Nota A2:")
Leia (A2)
media <- (A1+A2)/2
Escreval ("----------------------")
Escreval (" Média:", media)
Se (media >=6) entao
   Escreval (" ALUNO APROVADO (:")
Senao
     Escreval (" ALUNO REPROVADO ):")
FIMSE
Escreva ("-----------------------")
fimalgoritmo